import { expect, test } from "@playwright/test";
import sharp from "sharp";
import { ensureBootstrap } from "./helpers";
test("资料库：30 张先保全，5 张组成一条记忆，25 张仍在；原件直接加入相册", async ({ page }) => {
  await ensureBootstrap(page);
  await page.goto("/imports");
  const files = await Promise.all(Array.from({ length: 30 }, async (_, n) => ({ name: `IMG_${n}.jpg`, mimeType: "image/jpeg", buffer: await sharp({ create: { width: 40, height: 30, channels: 3, background: { r: n * 8, g: 100, b: 80 } } }).jpeg().toBuffer() })));
  await page.getByLabel("选择多份文件").setInputFiles(files);
  await page.getByRole("button", { name: "开始导入" }).click();
  await expect(page.getByText("服务器已完成 30/30")).toBeVisible({ timeout: 45000 });
  expect((await (await page.request.get("/api/mobile/v1/sync")).json()).events).toHaveLength(0);
  await page.goto("/library");
  const cards = page.getByRole("list", { name: "已保全的资料" }).locator(":scope > li");
  await expect(cards).toHaveCount(30);
  await expect(cards.first()).toContainText("时间待补");
  for (let i = 0; i < 5; i++) await cards.nth(i).getByRole("checkbox").check();
  await page.getByRole("button", { name: "加入一条新记忆", exact: true }).click();
  await expect(page).toHaveURL(/\/capture\?draft=/);
  await expect(page.locator("main ol > li")).toHaveCount(5);
  await page.getByLabel("标题", { exact: true }).fill("五张老照片的一件事");
  await page.getByLabel("发生时间", { exact: true }).fill("1980-08-12T18:30");
  await page.getByRole("button", { name: "保存为一条记忆" }).click();
  await expect(page.getByRole("link", { name: "查看这条记忆" })).toBeVisible();
  expect((await (await page.request.get("/api/mobile/v1/sync")).json()).events).toHaveLength(1);
  const assets = await (await page.request.get("/api/mobile/v1/assets")).json();
  expect(assets.entries).toHaveLength(30);
  expect(assets.entries.filter((a: { referenced: boolean }) => !a.referenced)).toHaveLength(25);
  await page.goto("/library");
  await cards.nth(6).getByRole("link").click();
  await page.getByRole("button", { name: /打开阅读器/ }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.getByRole("dialog").getByRole("button", { name: /关闭/ }).click();
  const album = await (await page.request.post("/api/collections", { data: { title: "直接看原件", kind: "album" } })).json();
  await page.getByRole("button", { name: "加入相册", exact: true }).click();
  await page.getByRole("button", { name: "直接看原件", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("已加入相册");
  await page.goto(`/collections/${album.id}`);
  await expect(page.locator("main")).toContainText("时间待补");
  await expect(page.locator('main a[href^="/library/"]')).toHaveCount(1);
  await page.locator('main a[href^="/library/"]').click();
  await page.getByRole("button", { name: "删除原件", exact: true }).click();
  await page.getByRole("button", { name: "确认永久删除原件", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("仍被草稿、记忆、相册或作品使用");
  const removable = assets.entries.find((a: { id: string; referenced: boolean }) => !a.referenced && !page.url().endsWith(a.id));
  await page.goto(`/library/${removable.id}`);
  await page.getByRole("button", { name: "删除原件", exact: true }).click();
  await page.getByRole("button", { name: "取消", exact: true }).click();
  expect((await page.request.get(`/api/media/${removable.id}`)).status()).toBe(200);
  await page.getByRole("button", { name: "删除原件", exact: true }).click();
  await page.getByRole("button", { name: "确认永久删除原件", exact: true }).click();
  await expect(page).toHaveURL(/\/library$/);
  await expect(cards).toHaveCount(29);
  expect((await page.request.get(`/api/media/${removable.id}`)).status()).toBe(404);

});
