import { waitForCapture, setCaptureMetadata } from "./helpers/capture";
import Database from "better-sqlite3";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { expect, test } from "@playwright/test";
import sharp from "sharp";
import { ensureBootstrap } from "./helpers";
test("导入脚本尚未就绪时禁用文件选择，就绪后文件只需选择一次", async ({ page, browser, baseURL }) => {
  await ensureBootstrap(page);
  const context = await browser.newContext({ baseURL, storageState: await page.context().storageState() });
  let release!: () => void;
  const scripts = new Promise<void>(resolve => { release = resolve; });
  try {
    const importing = await context.newPage();
    await importing.route(/\/_next\/static\/.*\.js(?:\?|$)/, async route => { await scripts; await route.continue(); });
    await importing.goto("/imports", { waitUntil: "commit" });
    const input = importing.getByLabel("选择多份文件");
    await expect(input).toBeVisible();
    await expect(input).toBeDisabled();
    release();
    await expect(input).toBeEnabled();
    await input.setInputFiles({ name: "一次选择.jpg", mimeType: "image/jpeg", buffer: await sharp({ create: { width: 20, height: 20, channels: 3, background: "blue" } }).jpeg().toBuffer() });
    await expect(importing.getByRole("button", { name: "开始导入", exact: true })).toBeVisible();
    await expect(importing.locator("main")).toContainText("一次选择.jpg");
  } finally { release(); await context.close(); }
});
test("资料库：30 张先保全，5 张组成一条记忆，25 张仍在；原件直接加入相册", async ({ page }) => {
  await ensureBootstrap(page);
  await page.goto("/imports");
  const files = await Promise.all(Array.from({ length: 30 }, async (_, n) => ({ name: `IMG_${n}.jpg`, mimeType: "image/jpeg", buffer: await sharp({ create: { width: 40, height: 30, channels: 3, background: { r: n * 8, g: 100, b: 80 } } }).jpeg().toBuffer() })));
  await expect(page.getByLabel("选择多份文件")).toBeEnabled();
  await page.getByLabel("选择多份文件").setInputFiles(files);
  await page.getByRole("button", { name: "开始导入" }).click();
  await expect(page.getByText("服务器已完成 30/30")).toBeVisible({ timeout: 45000 });
  expect((await (await page.request.get("/api/mobile/v1/sync")).json()).events).toHaveLength(0);
  await page.goto("/library");
  const cards = page.getByRole("list", { name: "已保全的资料" }).locator(":scope > li");
  await expect(cards).toHaveCount(30);
  await expect(cards.first()).toContainText("时间待补");
  for (let i = 0; i < 5; i++) await cards.nth(i).getByRole("checkbox").check();
  await page.getByRole("button", { name: "加入一条新记忆", exact: true }).click();
  await expect(page).toHaveURL(/\/capture\?draft=/);
  await expect(page.locator("main ol > li")).toHaveCount(5);
  await waitForCapture(page); await setCaptureMetadata(page, { title: "五张老照片的一件事" });
  await waitForCapture(page); await setCaptureMetadata(page, { occurredAt: new Date("1980-08-12T18:30:00+08:00").toISOString() });
  await page.getByRole("button", { name: "保存" }).click();
  await expect(page.getByRole("link", { name: "查看这条记忆" })).toBeVisible();
  expect((await (await page.request.get("/api/mobile/v1/sync")).json()).events).toHaveLength(1);
  const assets = await (await page.request.get("/api/mobile/v1/assets")).json();
  expect(assets.entries).toHaveLength(30);
  expect(assets.entries.filter((a: { referenced: boolean }) => !a.referenced)).toHaveLength(25);
  await page.goto("/library");
  await cards.nth(6).getByRole("link").click();
  await page.getByRole("button", { name: /打开阅读器/ }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.getByRole("dialog").getByRole("button", { name: /关闭/ }).click();
  const album = await (await page.request.post("/api/collections", { data: { title: "直接看原件", kind: "album" } })).json();
  await page.getByRole("button", { name: "加入相册", exact: true }).click();
  await page.getByRole("button", { name: "直接看原件", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("已加入相册");
  await page.goto(`/collections/${album.id}`);
  await expect(page.locator("main")).toContainText("时间待补");
  await expect(page.locator('main a[href^="/library/"]')).toHaveCount(1);
  await page.locator('main a[href^="/library/"]').click();
  await page.getByRole("button", { name: "删除原件", exact: true }).click();
  await page.getByRole("button", { name: "确认永久删除原件", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("仍被草稿、记忆、相册或作品使用");
  const removable = assets.entries.find((a: { id: string; referenced: boolean }) => !a.referenced && !page.url().endsWith(a.id));
  await page.goto(`/library/${removable.id}`);
  await page.getByRole("button", { name: "删除原件", exact: true }).click();
  await page.getByRole("button", { name: "取消", exact: true }).click();
  expect((await page.request.get(`/api/media/${removable.id}`)).status()).toBe(200);
  await page.getByRole("button", { name: "删除原件", exact: true }).click();
  await page.getByRole("button", { name: "确认永久删除原件", exact: true }).click();
  await expect(page).toHaveURL(/\/library$/);
  await expect(cards).toHaveCount(29);
  expect((await page.request.get(`/api/media/${removable.id}`)).status()).toBe(404);
  // An already shared original stays readable when its event becomes private,
  // but the library must no longer reveal or let another admin modify that event.
  const linked = assets.entries.find((a: { referenced: boolean }) => a.referenced);
  const db = new Database(path.join(process.cwd(), "data/e2e-asset-library/db/capsule.sqlite"));
  const token = randomUUID();
  let hiddenId: string;
  try {
    const event = db.prepare("select id,family_id from memory_event limit 1").get() as { id: string; family_id: string };
    hiddenId = event.id;
    db.prepare("update memory_event set visibility='private' where id=?").run(event.id);
    const actor = randomUUID();
    db.prepare("insert into user(id,name,email,role,family_id,created_at,updated_at) values (?,?,?,'admin',?,unixepoch(),unixepoch())").run(actor, "另一个管理员", `${actor}@fixture.invalid`, event.family_id);
    db.prepare("insert into session(id,token,user_id,expires_at,created_at,updated_at) values (?,?,?,unixepoch()+3600,unixepoch(),unixepoch())").run(randomUUID(), token, actor);
  } finally { db.close(); }
  await page.setExtraHTTPHeaders({ authorization: `Bearer ${token}` });
  await page.goto(`/library/${linked.id}`);
  await expect(page.locator("main")).not.toContainText("五张老照片的一件事");
  const otherHeaders = { authorization: `Bearer ${token}` };
  const otherDetail = await page.request.get(`/api/mobile/v1/assets/${linked.id}`, { headers: otherHeaders });
  expect(otherDetail.status()).toBe(200);
  expect(await otherDetail.json()).toMatchObject({ memories: [], referenced: false });
  expect((await page.request.get(`/api/media/${linked.id}`, { headers: otherHeaders })).status()).toBe(200);
  const denied = await page.request.post("/api/mobile/v1/assets", { headers: otherHeaders, data: { operation: "memory", targetId: hiddenId, assetIds: [linked.id] } });
  expect(denied.status()).toBe(404);
  expect((await page.request.get(`/api/mobile/v1/names?kind=memory_event&id=${hiddenId}`, { headers: otherHeaders })).status()).toBe(404);
  const renamed = await page.request.post("/api/mobile/v1/names", { headers: otherHeaders, data: { operation: "rename", kind: "memory_event", id: hiddenId, revision: 0, title: "不能越权改名" } });
  expect(renamed.status()).toBe(404);
});
