import { setCaptureMetadata, waitForCapture } from "./helpers/capture";
import { expect, test } from '@playwright/test';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { ensureBootstrap } from './helpers';
test.use({permissions:['microphone'],launchOptions:{args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']}});
test('restoring an unsent private recording preserves its audience in the form and saved contribution',async({page})=>{
  await ensureBootstrap(page);
  await page.goto('/capture');
  await page.getByLabel('写下这一刻').fill('这段声音只留给自己。');
  await page.getByRole('button',{name:'保存',exact:true}).click();
  const memoryLink=page.getByRole('link',{name:'查看这条记忆'});
  await expect(memoryLink).toBeVisible();
  const memoryPath=(await memoryLink.getAttribute('href'))!;
  await memoryLink.click();
  await page.locator('select[name="visibility"]').selectOption('private');
  const author=await page.locator('select[name="authorPersonId"]').inputValue();
  await page.getByRole('button',{name:'留段声音',exact:true}).click();
  await expect(page.getByText('录音中，完成后保存在本机。')).toBeVisible();
  await page.waitForTimeout(1200);
  await page.getByRole('button',{name:'完成录音'}).click();
  await expect(page.getByLabel('重听待保存的声音')).toBeVisible();
  await page.reload();
  await expect(page.getByLabel('重听待保存的声音')).toBeVisible();
  await expect(page.locator('select[name="visibility"]')).toHaveValue('private');
  await expect(page.locator('select[name="authorPersonId"]')).toHaveValue(author);
  await expect(page.getByText('· 仅自己 · 本机录音',{exact:false})).toBeVisible();
  await page.getByRole('button',{name:'保存声音',exact:true}).click();
  await expect(page.getByText('声音已保存到这条成长记录。')).toBeVisible();
  const memory=await(await page.request.get('/api/mobile/v1'+memoryPath)).json();
  const voices=memory.contributions.filter((c:{audioPath:string|null})=>c.audioPath);
  expect(voices).toHaveLength(1);
  expect(voices[0]).toMatchObject({authorPersonId:author,visibility:'private'});
});
test('record → first moment → family voice → birthday month → editable growing book',async({page,context})=>{
  test.setTimeout(120000);
  await ensureBootstrap(page);
  await page.setViewportSize({width:390,height:844});
  await page.goto('/capture');
  await page.getByLabel('写下这一刻').fill('今天第一次握紧爸爸的手指。');
  await page.locator('input[type="file"]').first().setInputFiles(['sample.jpg','sample.mp4'].map(file=>path.join(__dirname,'../fixtures',file)));
  await waitForCapture(page);
  await setCaptureMetadata(page, { occurredAt: new Date('2026-08-12T09:30' + ":00+08:00").toISOString() });
  await page.getByRole('button',{name:'保存',exact:true}).click();
  const link=page.getByRole('link',{name:'查看这条记忆'});await expect(link).toBeVisible();
  const memoryPath=(await link.getAttribute('href'))!;
  await link.click();
  await page.getByRole('button',{name:'第一次',exact:true}).click();
  await expect(page.getByRole('button',{name:'第一次',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.getByLabel('补充文字讲述').fill('爸爸记得你的小手很暖。');
  await page.getByRole('button',{name:'保存这段讲述'}).click();
  await expect(page.getByText('爸爸记得你的小手很暖。').first()).toBeVisible();
  await page.getByRole('button',{name:'留段声音',exact:true}).click();
  await expect(page.getByText('录音中，完成后保存在本机。')).toBeVisible();
  await page.waitForTimeout(1200);
  await page.getByRole('button',{name:'完成录音'}).click();
  await expect(page.getByLabel('重听待保存的声音')).toBeVisible();
  // Preserve the actual recorded browser audio through a page close and offline save failure.
  await page.reload();
  await expect(page.getByLabel('重听待保存的声音')).toBeVisible();
  await context.setOffline(true);
  await page.getByRole('button',{name:'保存声音',exact:true}).click();
  await expect(page.getByRole('button',{name:'重试保存声音'})).toBeEnabled();
  await context.setOffline(false);
  await page.getByRole('button',{name:'重试保存声音'}).click();
  await expect(page.getByText('声音已保存到这条成长记录。')).toBeVisible();
  const memory=await(await page.request.get('/api/mobile/v1'+memoryPath)).json();
  expect(memory.childPersonId).toBeTruthy();
  expect(memory.milestoneType).toBe('first_time');
  expect(memory.contributions.filter((c:{audioPath:string|null})=>c.audioPath)).toHaveLength(1);
  await page.goto('/timeline');
  await page.getByRole('link',{name:'第一个月',exact:true}).click();
  await expect(page.getByText('今天第一次握紧爸爸的手指。').first()).toBeVisible();
  await page.goto('/books');
  await page.getByRole('button',{name:'预览成长册',exact:true}).click();
  await expect(page).toHaveURL(/\/books\/[a-f0-9-]+$/);
  const bookUrl=page.url();
  await expect(page.getByText('小满的第一个月',{exact:true}).first()).toBeVisible();
  await expect(page.getByText('爸爸记得你的小手很暖。').first()).toBeVisible();
  await expect(page.getByRole('region',{name:'声音与视频'})).toBeVisible();
  await page.getByText('调整封面、寄语与收录内容',{exact:true}).click();
  await page.getByLabel('给宝宝的寄语').fill('愿你慢慢长大，我们慢慢陪你。');
  await expect(page.getByText('已自动保存，可以随时重开。')).toBeVisible();
  await page.goto('/books');
  await page.getByRole('button',{name:'打开成长册',exact:true}).click();
  await expect(page).toHaveURL(bookUrl);
  await expect(page.locator('p').filter({hasText:'愿你慢慢长大，我们慢慢陪你。'}).first()).toBeVisible();
  for (const width of [320,390,768,1440]) {
    await page.setViewportSize({width,height:900});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await page.screenshot({path:test.info().outputPath(`growth-book-${width}.png`),fullPage:true});
  }
  await page.getByText('导出与下载',{exact:true}).click();
  const panel=page.getByRole('region',{name:'出版与下载'});
  for (const format of ['PDF','EPUB']) {
    await panel.getByRole('button',{name:`生成 ${format}`,exact:true}).click();
    await expect(panel.getByText(/等待后台排版/)).toBeVisible();
    const worker=spawn(process.execPath,['.next/ops/worker.mjs','--once'],{cwd:process.cwd(),env:{...process.env,DATA_DIR:path.join(process.cwd(),'data/e2e-growth-journey')},stdio:['ignore','pipe','pipe']});
    let log='';worker.stdout.on('data',chunk=>{log+=chunk;});worker.stderr.on('data',chunk=>{log+=chunk;});
    expect(await new Promise((resolve,reject)=>{worker.once('error',reject);worker.once('close',resolve);}),log).toBe(0);
    expect(log).toContain('[book-worker] succeeded');
    await panel.getByRole('button',{name:'刷新出版状态'}).click();
    const link=panel.getByRole('link',{name:`下载 ${format}`,exact:true});await expect(link).toBeVisible();
    const pending=page.waitForEvent('download');await link.click();const download=await pending;
    expect(await download.failure()).toBeNull();expect(download.suggestedFilename()).toMatch(new RegExp(`\\.${format.toLowerCase()}$`));
  }
  await page.getByText('调整封面、寄语与收录内容',{exact:true}).click();
  await page.getByRole('button',{name:/^从本册移除：/}).click();
  await expect(page.getByText('已自动保存，可以随时重开。')).toBeVisible();
  await page.goto('/books');await page.getByRole('button',{name:'打开成长册',exact:true}).click();
  const book=await(await page.request.get('/api/books/projects/'+bookUrl.split('/').at(-1))).json();
  expect(book.blocks).toHaveLength(0);
  expect(book.subtitle).toBe('愿你慢慢长大，我们慢慢陪你。');
  expect((await page.request.get('/api/mobile/v1'+memoryPath)).status()).toBe(200);
});
