import { expect, test } from "@playwright/test";
import path from "node:path";
import { ensureBootstrap } from "./helpers";

test("long-lived mixed Web draft: offline save, closed page recovery, reorder, cover, one memory and one copy of each original", async ({ page, context }) => {
  await ensureBootstrap(page);
  await page.goto("/capture");
  await page.getByLabel("写下这一刻").fill("外公说年轻时在江边划船，今天录下来。正文检索词竹篙。");
  await page.getByLabel("标题", { exact: true }).fill("外公的江边往事");
  await page.getByLabel("发生时间", { exact: true }).fill("1980-08-12T18:30");
  await page.locator('input[type="file"]').first().setInputFiles(["sample-exif.jpg", "sample.jpg", "sample.wav"].map(name => path.join(__dirname, "../fixtures", name)));
  await expect(page.getByText("3 份原件已保存在本机", { exact: false })).toBeVisible();
  const before = await (await page.request.get("/api/mobile/v1/sync")).json();
  expect(before.events).toHaveLength(0);
  await context.setOffline(true);
  await page.getByRole("button", { name: "保留草稿，稍后继续" }).click();
  await expect(page.getByRole("status").filter({ hasText: "本机已保存 ·" })).toBeVisible();
  await page.close();
  await context.setOffline(false);
  const reopened = await context.newPage();
  await reopened.goto("/capture");
  await expect(reopened.getByLabel("写下这一刻")).toHaveValue("外公说年轻时在江边划船，今天录下来。正文检索词竹篙。");
  await expect(reopened.getByLabel("标题", { exact: true })).toHaveValue("外公的江边往事");
  await expect(reopened.locator("main ol > li")).toHaveCount(3);
  await expect(reopened.locator("audio")).toHaveCount(1);
  await reopened.locator("main ol > li").last().getByRole("button", { name: "上移" }).click();
  await reopened.locator("main ol > li").last().getByRole("button", { name: "设为封面" }).click();
  await reopened.getByRole("button", { name: "保存为一条记忆" }).click();
  await expect(reopened.getByRole("link", { name: "查看这条记忆" })).toBeVisible();
  const link = await reopened.getByRole("link", { name: "查看这条记忆" }).getAttribute("href");
  const id = link!.split("/").at(-1)!;
  const memory = await (await reopened.request.get(`/api/mobile/v1/memories/${id}`)).json();
  expect(memory.assets.map((a: { type: string }) => a.type)).toEqual(["image", "audio", "image"]);
  expect(memory.childPersonId).toBeNull();
  expect((await (await reopened.request.get("/api/mobile/v1/sync")).json()).events).toHaveLength(1);
  await reopened.getByRole("link", { name: "查看这条记忆" }).click();
  await expect(reopened.getByRole("heading", { name: "外公的江边往事", level: 1 })).toBeVisible();
  await expect(reopened.locator("main")).not.toContainText(/个月|出生当天/);
  await reopened.goto("/search?q=" + encodeURIComponent("竹篙"));
  await expect(reopened.getByRole("link", { name: /外公的江边往事/ })).toBeVisible();
});
