import { randomUUID } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterAll, expect, it, vi } from "vitest";
import { eq, sql } from "drizzle-orm";
import sharp from "sharp";
import type { FamilyContext } from "@/lib/family/context";
const dirs = [mkdtempSync(path.join(tmpdir(), "ftc-library-a-")), mkdtempSync(path.join(tmpdir(), "ftc-library-b-"))];
process.env.DATA_DIR = dirs[0]; process.env.AUTH_SECRET = "fictional-library-secret"; process.env.INITIAL_SETUP_TOKEN = "library-setup";
const { getDb, closeDatabase } = await import("@/db");
const { user, session } = await import("@/db/schema/auth");
const { memoryEvent } = await import("@/db/schema/memory");
const { asset } = await import("@/db/schema/asset");
const { performSetup } = await import("@/lib/auth/setup");
const { completeOnboarding, getUserBinding } = await import("@/lib/family/service");
const { ingestImage } = await import("@/lib/assets/ingest");
const { listLibraryAssets, getLibraryAsset, editLibraryAsset, addLibraryAssetsToDraft, addLibraryAssetsToMemory } = await import("@/lib/assets/library");
const { createCollection, addAssetsToCollection, saveCollection, listCollections } = await import("@/lib/collections/service");
const { saveDraft, publishDraft } = await import("@/lib/drafts/service");
afterAll(() => { closeDatabase(); dirs.forEach(dir => rmSync(dir, { recursive: true, force: true })); });
it("30 preserved photos stay readable without events; five form one memory and direct album references survive portable restore", async () => {
  expect((await performSetup({ token: "library-setup", displayName: "记录者", email: "library@fixture.invalid", password: "fictional-password" })).ok).toBe(true);
  const actor = getDb().select().from(user).get()!;
  const created = await completeOnboarding(actor.id, { familyName: "虚构资料家庭", timezone: "Asia/Shanghai", childDisplayName: "", childBirthDate: "", selfDisplayName: "外公", selfRelationToChild: "外公", selfIsGuardian: false });
  if (!created.ok) throw new Error(created.error);
  const binding = await getUserBinding(actor.id);
  const ctx: FamilyContext = { userId: actor.id, userName: actor.name, familyId: created.familyId, personId: binding.personId, role: binding.role, accountEnabled: true, isGuardian: false, familyTimezone: "Asia/Shanghai", childLaterUnlockAge: 18 };
  const assets: string[] = [];
  for (let n = 0; n < 30; n++) {
    const image = await ingestImage({ familyId: ctx.familyId, createdByUserId: ctx.userId, filename: `IMG_${n}.jpg`, declaredMime: "image/jpeg", buffer: await sharp({ create: { width: 40, height: 30, channels: 3, background: { r: n * 8, g: 100, b: 80 } } }).jpeg().toBuffer(), clientLastModifiedMs: null });
    if (image.status !== "stored") throw new Error(image.status); assets.push(image.asset.id);
  }
  expect(getDb().select().from(memoryEvent).all()).toHaveLength(0);
  const first = listLibraryAssets(ctx, { limit: 13 });
  expect(first.entries).toHaveLength(13);
  const second = listLibraryAssets(ctx, { limit: 30, cursor: first.nextCursor });
  expect(new Set([...first.entries, ...second.entries].map(a => a.id)).size).toBe(30);
  expect(first.entries.every(a => !a.referenced && a.capturedAt === null)).toBe(true);
  const original = getLibraryAsset(ctx, assets[0]!);
  expect(original.title).not.toContain("IMG_");
  const edited = editLibraryAsset(ctx, original.id, 0, { capturedAt: "1980-08-12T00:00:00Z", participantIds: [ctx.personId!] });
  expect(edited.technical.sha256).toBe(original.technical.sha256);
  expect(() => editLibraryAsset(ctx, original.id, 0, {})).toThrow("revision_conflict");
  expect(() => editLibraryAsset(ctx, original.id, 1, { participantIds: ["foreign-person"] })).toThrow("invalid_people");
  const draft = addLibraryAssetsToDraft(ctx, assets.slice(0, 5), randomUUID(), 0, randomUUID());
  const ready = saveDraft(ctx, draft.id, draft.revision, randomUUID(), { ...draft, title: "五张照片的一件事", occurredAt: "1980-08-12T00:00:00Z" });
  const published = publishDraft(ctx, ready.id, ready.revision);
  expect(getDb().select().from(memoryEvent).all()).toHaveLength(1);
  expect(listLibraryAssets(ctx).entries.filter(a => a.referenced)).toHaveLength(5);
  expect(listLibraryAssets(ctx).entries.filter(a => !a.referenced)).toHaveLength(25);
  addLibraryAssetsToMemory(ctx, [assets[0]!], published.memoryEventId!);
  const album = createCollection(ctx, "不需要日记的相册");
  const albumDetail = addAssetsToCollection(ctx, album, 1, assets.slice(5, 8));
  expect(albumDetail.items.map(i => i.assetId)).toEqual(assets.slice(5, 8));
  expect(albumDetail.items.every(i => i.memoryEventId === null && i.source?.occurredAt === "")).toBe(true);
  expect(listCollections(ctx).entries[0]?.count).toBe(3);
  const { getReadingManifest } = await import("@/lib/reading/service");
  const reading = getReadingManifest(ctx, "collection", album);
  expect(new Set(reading.media.map(a => a.id))).toEqual(new Set(assets.slice(5, 8)));
  expect(reading.chapters.flatMap(c => c.blocks).map(b => b.images).flat()).toEqual(assets.slice(5, 8));
  expect(reading.chapters.flatMap(c => c.blocks).every(b => b.memoryEventId === null)).toBe(true);
  const { createReadGrant, resolveReadGrant, readGrantIncludesAsset, listReadGrantEntries, revokeReadGrant } = await import("@/lib/family/read-grants");
  const grant = await createReadGrant(ctx, { collectionId: album }); if (!grant.ok) throw new Error(grant.error);
  const resolved = resolveReadGrant(grant.token)!;
  expect(listReadGrantEntries(resolved).flatMap(e => e.assets.map(a => a.assetId))).toEqual(assets.slice(5, 8));
  expect(readGrantIncludesAsset(resolved, assets[0]!)).toBe(false);
  const { contribution } = await import("@/db/schema/contribution");
  const privateRef = randomUUID();
  getDb().insert(contribution).values({ id: privateRef, memoryEventId: published.memoryEventId!, authorPersonId: ctx.personId!, rawText: "仅自己看", audioAssetId: assets[5]!, visibility: "private" }).run();
  expect(readGrantIncludesAsset(resolved, assets[5]!)).toBe(false);
  expect((await import("@/lib/books/projects/sources")).createBookSourceResolver(ctx, "family")("asset", assets[5]!).state.available).toBe(false);
  expect(getReadingManifest(ctx, "collection", album).audience).toBe("personal");
  getDb().delete(contribution).where(eq(contribution.id, privateRef)).run();
  revokeReadGrant(ctx, grant.grantId);
  expect(readGrantIncludesAsset(resolved, assets[6]!)).toBe(false);
  expect(listReadGrantEntries(resolved)).toEqual([]);
  const removed = saveCollection(ctx, album, albumDetail.revision, { ...albumDetail, items: albumDetail.items.slice(1), coverAssetId: assets[6] });
  expect(removed.items).toHaveLength(2);
  expect(getLibraryAsset(ctx, assets[5]!).id).toBe(assets[5]);
  expect(getDb().select().from(asset).where(isOriginal()).all()).toHaveLength(30);
  const token = randomUUID(); getDb().insert(session).values({ id: randomUUID(), token, userId: actor.id, expiresAt: new Date(Date.now() + 3600000) }).run();
  const req = new Request("http://localhost/api/mobile/v1/assets", { headers: { authorization: `Bearer ${token}` } });
  const api = await import("@/app/api/mobile/v1/assets/route");
  expect((await api.GET(req)).status).toBe(200);
  expect((await (await api.GET(req)).json()).entries).toHaveLength(30);
  expect(() => getLibraryAsset(ctx, "foreign-asset")).toThrow("not_found");
  const viewerId = randomUUID();
  getDb().insert(user).values({ id: viewerId, familyId: ctx.familyId, role: "viewer", name: "只读家人", email: "viewer-library@fixture.invalid" }).run();
  const viewer = { ...ctx, userId: viewerId, personId: null, role: "viewer" as const };
  expect(listLibraryAssets(viewer).entries).toHaveLength(30);
  expect(() => editLibraryAsset(viewer, original.id, 1, {})).toThrow("forbidden");
  expect(() => addLibraryAssetsToMemory(viewer, [assets[0]!], published.memoryEventId!)).toThrow("forbidden");
  const backup = await (await import("@/lib/export/service")).buildFamilyExport(ctx.familyId, { actorUserId: ctx.userId });
  const bytes = readFileSync(backup.filePath);
  closeDatabase(); process.env.DATA_DIR = dirs[1]; vi.resetModules();
  const target = await import("@/db");
  try {
    await (await import("@/lib/auth/setup")).performSetup({ token: "library-setup", displayName: "恢复维护者", email: "restore-library@fixture.invalid", password: "fictional-password" });
    const operator = target.getDb().get<{ id: string }>(sql`select id from user`)!;
    await (await import("@/lib/restore/service")).restoreFromZip(bytes, operator.id);
    const restored = target.getDb().select().from(asset).where(eq(asset.id, original.id)).get()!;
    expect(JSON.parse(restored.participantIdsJson)).toEqual([ctx.personId]);
    expect(restored.metadataRevision).toBe(1);
    expect(restored.sha256).toBe(original.technical.sha256);
    expect(target.getDb().all(sql`select asset_id from collection_item where collection_id=${album} order by position`)).toEqual(assets.slice(6, 8).map(asset_id => ({ asset_id })));
    expect(target.getDb().all(sql`pragma foreign_key_check`)).toEqual([]);
  } finally { target.closeDatabase(); }
});
function isOriginal() { return sql`${asset.originalAssetId} is null`; }
