import { randomUUID } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { eq, sql } from "drizzle-orm";
import { afterAll, expect, it, vi } from "vitest";
import JSZip from "jszip";
import type { FamilyContext } from "@/lib/family/context";
const dirs = [mkdtempSync(path.join(tmpdir(), "ftc-delete-")), mkdtempSync(path.join(tmpdir(), "ftc-delete-restore-"))];
process.env.DATA_DIR = dirs[0]; process.env.AUTH_SECRET = "fictional-deletion-secret"; process.env.INITIAL_SETUP_TOKEN = "asset-delete";
const { getDb, closeDatabase } = await import("@/db");
const { user, session } = await import("@/db/schema/auth");
const { asset } = await import("@/db/schema/asset");
const { assetDeletion } = await import("@/db/schema/asset-deletion");
const { performSetup } = await import("@/lib/auth/setup");
const { completeOnboarding, getUserBinding } = await import("@/lib/family/service");
const { ingestImage } = await import("@/lib/assets/ingest");
const { getAssetStorage } = await import("@/lib/assets/storage");
const { deleteLibraryAsset } = await import("@/lib/assets/deletion");
const { listLibraryAssets, getLibraryAsset, addLibraryAssetsToDraft } = await import("@/lib/assets/library");
afterAll(() => { closeDatabase(); dirs.forEach(dir => rmSync(dir, { recursive: true, force: true })); });
it("guards live permissions and every user reference; deletion survives a disk failure/restart and portable restore without restoring originals", async () => {
  expect((await performSetup({ token: "asset-delete", displayName: "记录者", email: "delete@fixture.invalid", password: "fictional-password" })).ok).toBe(true);
  const actor = getDb().select().from(user).get()!;
  const created = await completeOnboarding(actor.id, { familyName: "虚构删除家庭", timezone: "Asia/Shanghai", childDisplayName: "", childBirthDate: "", selfDisplayName: "家人", selfRelationToChild: "", selfIsGuardian: false });
  if (!created.ok) throw new Error(created.error);
  const binding = await getUserBinding(actor.id);
  const ctx: FamilyContext = { userId: actor.id, userName: actor.name, familyId: created.familyId, personId: binding.personId, role: binding.role, accountEnabled: true, isGuardian: false, familyTimezone: "Asia/Shanghai", childLaterUnlockAge: 18 };
  const original = await ingestImage({ familyId: ctx.familyId, createdByUserId: actor.id, filename: "IMG_original.jpg", declaredMime: "image/jpeg", buffer: readFileSync(path.join(__dirname, "../fixtures/sample.jpg")) });
  if (original.status !== "stored") throw new Error(original.status);
  const id = original.asset.id, storage = getAssetStorage();
  const tree = getDb().select().from(asset).all(); expect(tree.length).toBeGreaterThan(1);
  const viewerId = randomUUID(), editorId = randomUUID();
  getDb().insert(user).values([{ id: viewerId, name: "只读", email: "delete-viewer@fixture.invalid", familyId: ctx.familyId, role: "viewer" }, { id: editorId, name: "其他编辑", email: "delete-editor@fixture.invalid", familyId: ctx.familyId, role: "editor" }]).run();
  const viewer = { ...ctx, userId: viewerId, personId: null, role: "viewer" as const };
  const editor = { ...ctx, userId: editorId, personId: null, role: "editor" as const };
  expect(getLibraryAsset(viewer, id).canDelete).toBe(false);
  expect(getLibraryAsset(editor, id).canDelete).toBe(false);
  expect(() => deleteLibraryAsset(viewer, id, true)).toThrow("forbidden");
  expect(() => deleteLibraryAsset(editor, id, true)).toThrow("forbidden");
  expect(() => deleteLibraryAsset(ctx, id, false)).toThrow("confirmation_required");
  getDb().insert(user).values({ id: randomUUID(), name: "备用管理员", email: "delete-admin@fixture.invalid", familyId: ctx.familyId, role: "admin" }).run();
  getDb().update(user).set({ disabledAt: new Date() }).where(eq(user.id, ctx.userId)).run();
  expect(() => deleteLibraryAsset(ctx, id, true)).toThrow("forbidden");
  getDb().update(user).set({ disabledAt: null }).where(eq(user.id, ctx.userId)).run();
  const draft = addLibraryAssetsToDraft(ctx, [id], randomUUID(), 0, randomUUID());
  expect(() => deleteLibraryAsset(ctx, id, true)).toThrow("asset_in_use");
  getDb().run(sql`delete from draft where id=${draft.id}`);
  // Any future foreign-key reference is guarded, even SET NULL relationships
  // and a user reference to a derivative instead of the original.
  getDb().run(sql`create table future_reference (asset_id text references asset(id) on delete set null)`);
  getDb().run(sql`insert into future_reference values (${tree.find(a => a.originalAssetId)?.id})`);
  expect(() => deleteLibraryAsset(ctx, id, true)).toThrow("asset_in_use");
  getDb().run(sql`drop table future_reference`);
  const albumService = await import("@/lib/collections/service");
  const album = albumService.createCollection(ctx, "仍使用原件的相册");
  const albumDetail = albumService.addAssetsToCollection(ctx, album, 1, [id]);
  expect(() => deleteLibraryAsset(ctx, id, true)).toThrow("asset_in_use");
  albumService.saveCollection(ctx, album, albumDetail.revision, { ...albumDetail, items: [], coverAssetId: null });
  const inbox = await (await import("@/lib/inbox/service")).createInboxItemForAsset(ctx.familyId, original.asset);
  expect(tree.every(a => storage.exists(a.storageKey))).toBe(true);
  const remove = vi.spyOn(storage, "delete").mockImplementation(() => { throw new Error("fixture disk I/O failure"); });
  const token = randomUUID(); getDb().insert(session).values({ id: randomUUID(), token, userId: ctx.userId, expiresAt: new Date(Date.now() + 3600000) }).run();
  const route = await import("@/app/api/mobile/v1/assets/[id]/route");
  const request = new Request(`http://localhost/api/mobile/v1/assets/${id}`, { method: "DELETE", headers: { authorization: `Bearer ${token}`, "content-type": "application/json" }, body: JSON.stringify({ confirmed: true }) });
  const removed = await route.DELETE(request, { params: Promise.resolve({ id }) });
  expect(removed.status).toBe(202); expect(await removed.json()).toEqual({ deleted: true, cleanupPending: true });
  expect(() => getLibraryAsset(ctx, id)).toThrow("not_found");
  expect(getDb().select().from(asset).all()).toEqual([]);
  expect(getDb().get(sql`select status from inbox_item where id=${inbox.id}`)).toEqual({ status: "discarded" });
  expect(listLibraryAssets(ctx).pendingDeletions).toEqual([{ id }]);
  expect(listLibraryAssets(viewer).pendingDeletions).toEqual([]);
  expect(tree.every(a => storage.exists(a.storageKey))).toBe(true);
  closeDatabase(); remove.mockRestore(); // Re-open an actual database after the failed cleanup.
  expect(listLibraryAssets(ctx).pendingDeletions).toEqual([{ id }]);
  expect(deleteLibraryAsset(ctx, id, true)).toEqual({ deleted: true, cleanupPending: false });
  expect(tree.some(a => storage.exists(a.storageKey))).toBe(false);
  expect(deleteLibraryAsset(ctx, id, true)).toEqual({ deleted: true, cleanupPending: false });
  const receipt = getDb().select().from(assetDeletion).get()!;
  expect(receipt.storageKeysJson).toBe("[]"); expect(receipt.cleanedAt).not.toBeNull();
  const backup = await (await import("@/lib/export/service")).buildDisasterExport(ctx.familyId, { actorUserId: ctx.userId });
  const bytes = readFileSync(backup.filePath), zip = await JSZip.loadAsync(bytes);
  expect(JSON.parse(await zip.file("family-time-capsule-export/asset-deletions.json")!.async("string"))).toEqual([{ assetId: id, sha256: original.asset.sha256, deletedAt: receipt.deletedAt }]);
  closeDatabase(); process.env.DATA_DIR = dirs[1]; vi.resetModules();
  const target = await import("@/db");
  try {
    await (await import("@/lib/auth/setup")).performSetup({ token: "asset-delete", displayName: "恢复维护者", email: "delete-restore@fixture.invalid", password: "fictional-password" });
    const operator = target.getDb().get<{ id: string }>(sql`select id from user`)!;
    await (await import("@/lib/restore/service")).restoreFromZip(bytes, operator.id);
    expect(target.getDb().all(sql`select id from asset`)).toEqual([]);
    expect(target.getDb().get(sql`select asset_id,sha256,deleted_at,requested_by_user_id,storage_keys_json from asset_deletion`)).toEqual({ asset_id: id, sha256: original.asset.sha256, deleted_at: receipt.deletedAt, requested_by_user_id: null, storage_keys_json: "[]" });
    expect(target.getDb().all(sql`pragma foreign_key_check`)).toEqual([]);
  } finally { target.closeDatabase(); }
});
