import { randomUUID } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterAll, expect, it, vi } from "vitest";
import { eq, sql } from "drizzle-orm";
import JSZip from "jszip";
import type { FamilyContext } from "@/lib/family/context";
const dirs = [mkdtempSync(path.join(tmpdir(), "ftc-draft-a-")), mkdtempSync(path.join(tmpdir(), "ftc-draft-b-"))];
process.env.DATA_DIR = dirs[0];
process.env.AUTH_SECRET = "fictional-draft-secret-only";
process.env.INITIAL_SETUP_TOKEN = "draft-setup";
const { getDb, closeDatabase } = await import("@/db");
const { user, session } = await import("@/db/schema/auth");
const { memoryEvent, memoryEventAsset } = await import("@/db/schema/memory");
const { asset } = await import("@/db/schema/asset");
const { performSetup } = await import("@/lib/auth/setup");
const { completeOnboarding, getUserBinding } = await import("@/lib/family/service");
const { ingestImage, ingestMedia } = await import("@/lib/assets/ingest");
const { emptyDraftContent } = await import("@/lib/drafts/model");
const { saveDraft, getDraft, listDrafts, publishDraft, discardDraft } = await import("@/lib/drafts/service");
const { getMemoryEventDetail } = await import("@/lib/memories/service");
const { searchFamily, rebuildSearchIndex } = await import("@/lib/search/service");
const { buildFamilyExport } = await import("@/lib/export/service");
const { PUT, GET } = await import("@/app/api/mobile/v1/drafts/[id]/route");
const { POST } = await import("@/app/api/mobile/v1/drafts/[id]/publish/route");
afterAll(() => { closeDatabase(); dirs.forEach(dir => rmSync(dir, { recursive: true, force: true })); });

it("persistent mixed draft survives reopen, HTTP retries, reordering, permission checks, publication and portable restore", async () => {
  expect((await performSetup({ token: "draft-setup", displayName: "记录者", email: "draft@fixture.invalid", password: "fictional-password" })).ok).toBe(true);
  const actor = getDb().select().from(user).get()!;
  const created = await completeOnboarding(actor.id, { familyName: "虚构草稿家庭", timezone: "Asia/Shanghai", childDisplayName: "", childBirthDate: "", selfDisplayName: "外公", selfRelationToChild: "外公", selfIsGuardian: false });
  if (!created.ok) throw new Error(created.error);
  const binding = await getUserBinding(actor.id);
  const ctx: FamilyContext = { userId: actor.id, userName: actor.name, familyId: created.familyId, personId: binding.personId, role: binding.role, accountEnabled: true, isGuardian: false, familyTimezone: "Asia/Shanghai", childLaterUnlockAge: 18 };
  const assets = [];
  for (const name of ["sample-exif.jpg", "sample.jpg"]) {
    const image = await ingestImage({ familyId: ctx.familyId, createdByUserId: ctx.userId, filename: name, declaredMime: "image/jpeg", buffer: readFileSync(path.join(__dirname, "../fixtures", name)), clientLastModifiedMs: null });
    if (image.status !== "stored") throw new Error(image.status); assets.push(image.asset.id);
  }
  const audio = await ingestMedia({ kind: "audio", familyId: ctx.familyId, createdByUserId: ctx.userId, filename: "口述.wav", declaredMime: "audio/wav", buffer: readFileSync(path.join(__dirname, "../fixtures/sample.wav")), clientLastModifiedMs: null });
  if (audio.status !== "stored") throw new Error(audio.status); assets.push(audio.asset.id);
  const id = randomUUID();
  const content = { ...emptyDraftContent(), title: "一件混合记录", text: "江边划船的完整回忆只在正文里", occurredAt: "1980-08-12T09:30:00.000Z", participantIds: [ctx.personId!], items: assets.map(assetId => ({ id: randomUUID(), assetId, localCaptureRef: null, caption: "原始顺序" })) };
  const mutationId = randomUUID();
  const saved = saveDraft(ctx, id, 0, mutationId, content);
  expect(saved.revision).toBe(1);
  expect(saveDraft(ctx, id, 0, mutationId, content)).toEqual(saved);
  // A second real connection reads the committed aggregate while the auth singleton stays live.
  const { default: Database } = await import("better-sqlite3");
  const reopened = new Database(path.join(dirs[0]!, "db/capsule.sqlite"));
  expect(reopened.prepare("select text from draft where id=?").get(id)).toEqual({ text: content.text });
  reopened.close();
  expect(getDraft(ctx, id)).toEqual(saved);
  expect(getDb().select().from(memoryEvent).all()).toHaveLength(0);
  const reversed = { ...content, items: [...content.items].reverse(), coverItemId: content.items[1]!.id };
  const edited = saveDraft(ctx, id, 1, randomUUID(), reversed);
  expect(() => saveDraft(ctx, id, 1, randomUUID(), content)).toThrow("revision_conflict");
  const stranger = randomUUID();
  getDb().insert(user).values({ id: stranger, name: "另一位记录者", email: "another@fixture.invalid", familyId: ctx.familyId, role: "editor" }).run();
  const other = { ...ctx, userId: stranger, personId: null, role: "editor" as const };
  expect(listDrafts(other)).toEqual([]);
  expect(() => getDraft(other, id)).toThrow("not_found");
  expect(() => saveDraft(ctx, randomUUID(), 0, randomUUID(), { ...content, participantIds: ["foreign-person"] })).toThrow("invalid_person");
  expect(() => saveDraft(ctx, randomUUID(), 0, randomUUID(), { ...content, items: [{ ...content.items[0], id: randomUUID(), assetId: "foreign-asset" }] })).toThrow("asset_unavailable");
  const token = randomUUID();
  getDb().insert(session).values({ id: randomUUID(), token, userId: actor.id, expiresAt: new Date(Date.now() + 3600000) }).run();
  const request = (body: unknown, method = "PUT") => new Request(`http://localhost/api/mobile/v1/drafts/${id}`, { method, headers: { authorization: `Bearer ${token}`, "content-type": "application/json" }, body: JSON.stringify(body) });
  const route = { params: Promise.resolve({ id }) };
  expect((await GET(new Request(`http://localhost/api/mobile/v1/drafts/${id}`, { headers: { authorization: `Bearer ${token}` } }), route)).status).toBe(200);
  expect((await PUT(request({ expectedRevision: 0, mutationId: randomUUID(), content }), route)).status).toBe(409);
  const response = await POST(request({ expectedRevision: edited.revision }, "POST"), route);
  expect(response.status).toBe(200);
  const published = await response.json();
  expect(publishDraft(ctx, id, edited.revision)).toEqual(published);
  expect(getDb().select().from(memoryEvent).all()).toHaveLength(1);
  const detail = (await getMemoryEventDetail(ctx.familyId, published.memoryEventId))!;
  expect(detail.assets.map(a => a.id)).toEqual([...assets].reverse());
  expect(detail.event.coverAssetId).toBe(assets[1]);
  expect(detail.event.childPersonId).toBeNull();
  expect(detail.sourceNotes.map(n => n.rawText)).toEqual([content.text]);
  expect(searchFamily(ctx, { q: "划船" }).events.map(e => e.id)).toContain(detail.event.id);
  rebuildSearchIndex();
  expect(searchFamily(ctx, { q: "划船" }).events.map(e => e.id)).toContain(detail.event.id);
  // Inbox is a projection of the same aggregate, including closing transitions.
  const { submitDraftForReview } = await import("@/lib/drafts/service");
  const { mergeInboxEntries } = await import("@/lib/memories/service");
  const { discardInboxItem, getInboxEntry } = await import("@/lib/inbox/service");
  const textDraft = () => saveDraft(ctx, randomUUID(), 0, randomUUID(), { ...emptyDraftContent(), text: "另一段讲述", occurredAt: content.occurredAt });
  const offeredA = textDraft(), offeredB = textDraft();
  submitDraftForReview(ctx, offeredA.id, offeredA.revision);
  submitDraftForReview(ctx, offeredB.id, offeredB.revision);
  const merged = await mergeInboxEntries(ctx.familyId, [offeredA.id, offeredB.id], { title: "一起讲的一件事", occurredAt: new Date(content.occurredAt) });
  expect(merged.ok).toBe(true);
  if (!merged.ok) throw new Error(merged.error);
  expect(getDraft(ctx, offeredA.id)).toMatchObject({ status: "published", memoryEventId: merged.eventId });
  expect(publishDraft(ctx, offeredB.id, offeredB.revision).memoryEventId).toBe(merged.eventId);
  expect(await discardInboxItem(ctx.familyId, offeredA.id)).toBe(false);
  const offeredC = textDraft();
  const reviewC = submitDraftForReview(ctx, offeredC.id, offeredC.revision);
  discardDraft(ctx, offeredC.id, reviewC.revision);
  expect((await getInboxEntry(ctx.familyId, offeredC.id))?.item.status).toBe("discarded");
  const offeredD = textDraft();
  submitDraftForReview(ctx, offeredD.id, offeredD.revision);
  expect(await discardInboxItem(ctx.familyId, offeredD.id)).toBe(true);
  expect(() => publishDraft(ctx, offeredD.id, offeredD.revision)).toThrow("revision_conflict");
  const { GET: readMetadata } = await import("@/app/api/media/[assetId]/metadata/route");
  const metadataRequest = new Request("http://localhost/api/media/metadata", { headers: { authorization: `Bearer ${token}` } });
  const metadata = await readMetadata(metadataRequest, { params: Promise.resolve({ assetId: assets[0]! }) });
  expect(metadata.status).toBe(200);
  expect(await metadata.json()).toMatchObject({ id: assets[0], type: "image", mimeType: "image/jpeg" });
  expect((await readMetadata(metadataRequest, { params: Promise.resolve({ assetId: "another-family-asset" }) })).status).toBe(404);
  const draft2 = saveDraft(ctx, randomUUID(), 0, randomUUID(), { ...content, items: [{ ...content.items[0]!, id: randomUUID() }] });
  const draft3 = saveDraft(ctx, randomUUID(), 0, randomUUID(), { ...emptyDraftContent(), text: "尚未填时间" });
  expect(() => publishDraft(ctx, draft3.id, draft3.revision)).toThrow("occurred_at_required");
  discardDraft(ctx, draft3.id, draft3.revision);
  expect(getDraft(ctx, draft3.id).status).toBe("discarded");
  expect(getDb().select().from(asset).where(sql`${asset.originalAssetId} is null`).all()).toHaveLength(3);
  // R03: the same native DTO is published through authenticated HTTP and remains
  // unknown through independent database reopen, export and a fresh-instance restore.
  const unknownId = randomUUID();
  const unknownRoute = { params: Promise.resolve({ id: unknownId }) };
  const unknownContent = { ...emptyDraftContent(), title: "记不得日期", text: "那次江边散步的正文", occurredAtPrecision: "unknown" as const };
  const unknownSaved = await PUT(request({ expectedRevision: 0, mutationId: randomUUID(), content: unknownContent }), unknownRoute);
  expect(unknownSaved.status).toBe(200);
  expect(await unknownSaved.json()).toMatchObject({ occurredAt: null, occurredAtPrecision: "unknown" });
  const unknownPublished = await POST(request({ expectedRevision: 1 }, "POST"), unknownRoute);
  expect(unknownPublished.status).toBe(200);
  const unknownMemory = await unknownPublished.json();
  expect(unknownMemory).toMatchObject({ status: "published", occurredAt: null, occurredAtPrecision: "unknown" });
  const reopenedUnknown = new Database(path.join(dirs[0]!, "db/capsule.sqlite"));
  expect(reopenedUnknown.prepare("select occurred_at, occurred_at_precision from draft where id=?").get(unknownId)).toEqual({ occurred_at: null, occurred_at_precision: "unknown" });
  reopenedUnknown.close();
  const backup = await buildFamilyExport(ctx.familyId, { actorUserId: ctx.userId });
  const bytes = readFileSync(backup.filePath);
  const zip = await JSZip.loadAsync(bytes);
  expect(Object.keys(zip.files).filter(name => name.endsWith("drafts.json"))).toHaveLength(1);
  closeDatabase(); process.env.DATA_DIR = dirs[1]; vi.resetModules();
  const target = await import("@/db");
  try {
    await (await import("@/lib/auth/setup")).performSetup({ token: "draft-setup", displayName: "恢复维护者", email: "restore@fixture.invalid", password: "fictional-password" });
    const operator = target.getDb().get<{ id: string }>(sql`select id from user`)!;
    await (await import("@/lib/restore/service")).restoreFromZip(bytes, operator.id);
    expect(target.getDb().all(sql`pragma foreign_key_check`)).toEqual([]);
    expect(target.getDb().get(sql`select occurred_at, occurred_at_precision from draft where id=${unknownId}`)).toEqual({ occurred_at: null, occurred_at_precision: "unknown" });
    const restoredUnknown = await (await import("@/lib/memories/service")).getMemoryEventDetail(ctx.familyId, unknownMemory.memoryEventId);
    expect(restoredUnknown?.event.occurredAtPrecision).toBe("unknown");
    expect(restoredUnknown?.sourceNotes.map(n => n.rawText)).toEqual([unknownContent.text]);
    const restored = target.getDb().select().from(memoryEventAsset).where(eq(memoryEventAsset.memoryEventId, detail.event.id)).all().sort((a, b) => a.sortOrder - b.sortOrder);
    expect(restored.map(a => a.assetId)).toEqual([...assets].reverse());
    expect(restored.map(a => a.caption)).toEqual(["原始顺序", "原始顺序", "原始顺序"]);
    const row = target.getDb().get<{ author_user_id: string | null; author_person_id: string }>(sql`select author_user_id, author_person_id from draft where id=${draft2.id}`)!;
    expect(row).toEqual({ author_user_id: null, author_person_id: ctx.personId });
    // Restore operator never becomes the author. Rebinding the original Person resumes the draft.
    const resumedUser = randomUUID();
    target.getDb().insert(user).values({ id: resumedUser, name: "恢复原作者", email: "resumed@fixture.invalid", familyId: ctx.familyId, personId: ctx.personId, role: "editor" }).run();
    const restoredDraft = (await import("@/lib/drafts/service")).getDraft({ ...ctx, userId: resumedUser, role: "editor" }, draft2.id);
    expect(restoredDraft.text).toBe(content.text);
    expect(restoredDraft.items.map(i => i.assetId)).toEqual([assets[0]]);
  } finally { target.closeDatabase(); }
});
