import { randomUUID } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterAll, expect, it } from "vitest";
import { sql } from "drizzle-orm";
import type { FamilyContext } from "@/lib/family/context";
const dir = mkdtempSync(path.join(tmpdir(), "ftc-private-body-"));
process.env.DATA_DIR = dir;
process.env.AUTH_SECRET = "synthetic-private-body-secret";
const { getDb, closeDatabase } = await import("@/db");
const { family } = await import("@/db/schema/family");
const { user, session } = await import("@/db/schema/auth");
const { emptyDraftContent } = await import("@/lib/drafts/model");
const { PUT } = await import("@/app/api/mobile/v1/drafts/[id]/route");
const { POST } = await import("@/app/api/mobile/v1/drafts/[id]/publish/route");
const { getVisibleMemoryEventDetail, updateMemoryEvent, updateMemoryEventVisibility } = await import("@/lib/memories/service");
const { searchFamily, rebuildSearchIndex } = await import("@/lib/search/service");
afterAll(() => { closeDatabase(); rmSync(dir, { recursive: true, force: true }); });
it("R08: private HTTP publication keeps its body through draft removal, index rebuild, metadata edit and reader changes", async () => {
  const db = getDb();
  db.insert(family).values({ id: "family", name: "虚构正文家庭" }).run();
  for (const id of ["a", "b", "c"]) db.insert(user).values({ id, name: id, email: `${id}@fixture.invalid`, familyId: "family", role: id === "c" ? "admin" : "editor" }).run();
  db.insert(session).values({ id: "session", token: "token", userId: "a", expiresAt: new Date(Date.now() + 3600000) }).run();
  const context: FamilyContext = { familyId: "family", userId: "a", userName: "a", personId: null, role: "editor", accountEnabled: true, isGuardian: false, familyTimezone: "UTC", childLaterUnlockAge: 18 };
  const body = "紫藤花下那封没有日期的信\n\n原文的第二段，也要完整保留。";
  const id = randomUUID(), route = { params: Promise.resolve({ id }) };
  const request = (payload: unknown) => new Request("http://localhost/api/mobile/v1/drafts", { method: "POST", headers: { authorization: "Bearer token", "content-type": "application/json" }, body: JSON.stringify(payload) });
  expect((await PUT(request({ expectedRevision: 0, mutationId: randomUUID(), content: { ...emptyDraftContent(), title: "一个简短标题", text: body, visibility: "private", occurredAtPrecision: "unknown" } }), route)).status).toBe(200);
  const published = await POST(request({ expectedRevision: 1 }), route);
  expect(published.status).toBe(200);
  const eventId = (await published.json()).memoryEventId;
  expect((await getVisibleMemoryEventDetail(context, eventId))?.sourceNotes.map(n => n.rawText)).toEqual([body]);
  db.run(sql`delete from draft where id=${id}`);
  rebuildSearchIndex();
  expect(searchFamily(context, { q: "紫藤花" }).events.map(e => e.id)).toContain(eventId);
  const stranger = { ...context, userId: "c", role: "admin" as const };
  expect(await getVisibleMemoryEventDetail(stranger, eventId)).toBeUndefined();
  expect(searchFamily(stranger, { q: "紫藤花" }).events).toEqual([]);
  expect((await updateMemoryEvent("family", eventId, "a", { title: "改过的标题" })).ok).toBe(true);
  expect((await getVisibleMemoryEventDetail(context, eventId))?.sourceNotes.map(n => n.rawText)).toEqual([body]);
  const { createBookSourceResolver } = await import("@/lib/books/projects/sources");
  expect(createBookSourceResolver(context, "personal")("memory", eventId).text).toBe(body);
  expect(createBookSourceResolver(stranger, "personal")("memory", eventId).state.available).toBe(false);
  expect(createBookSourceResolver(context, "family")("memory", eventId).state.available).toBe(false);
  const event = (await getVisibleMemoryEventDetail(context, eventId))!.event;
  expect((await updateMemoryEventVisibility(context, eventId, "members", ["b"], event.titleRevision)).ok).toBe(true);
  expect((await getVisibleMemoryEventDetail({ ...context, userId: "b" }, eventId))?.sourceNotes.map(n => n.rawText)).toEqual([body]);
  const { buildActorExport } = await import("@/lib/export/service");
  const { default: JSZip } = await import("jszip");
  const exportC = await buildActorExport(stranger);
  const zipC = await JSZip.loadAsync(readFileSync(exportC.filePath));
  const exportedText = (await Promise.all(Object.values(zipC.files).filter(f => !f.dir && /\.(json|md)$/.test(f.name)).map(f => f.async("string")))).join("\n");
  expect(exportedText).not.toContain("紫藤花");
  expect(db.get<{ snapshot_json: string }>(sql`select snapshot_json from memory_event_revision where memory_event_id=${eventId}`)?.snapshot_json).toContain("紫藤花");
});
