import { randomUUID } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import JSZip from "jszip";
import { eq, sql } from "drizzle-orm";
import { afterAll, expect, it, vi } from "vitest";
import type { FamilyContext } from "@/lib/family/context";

const dirs = [mkdtempSync(path.join(tmpdir(), "ftc-grandparent-a-")), mkdtempSync(path.join(tmpdir(), "ftc-grandparent-b-"))];
process.env.DATA_DIR = dirs[0];
process.env.AUTH_SECRET = "fictional-grandparent-test-secret-only";
process.env.INITIAL_SETUP_TOKEN = "grandparent-setup";
const { getDb, closeDatabase } = await import("@/db");
const { user, session } = await import("@/db/schema/auth");
const { person } = await import("@/db/schema/family");
const { memoryEvent } = await import("@/db/schema/memory");
const { performSetup } = await import("@/lib/auth/setup");
const { completeOnboarding, getUserBinding, listPeople, addPerson } = await import("@/lib/family/service");
const { ingestMedia } = await import("@/lib/assets/ingest");
const { createTextInboxItem, createInboxItemForAsset, getInboxEntry } = await import("@/lib/inbox/service");
const { mergeInboxEntries, confirmInboxEntry, updateMemoryEvent, getMemoryEventDetail, getTimelinePage } = await import("@/lib/memories/service");
const { getMobileMemory } = await import("@/lib/mobile/product");
const { getMobileSyncPage } = await import("@/lib/mobile/sync");
const { getHomeDashboard } = await import("@/lib/home/service");
const { getCalendarMonth } = await import("@/lib/memories/calendar");
const { searchFamily } = await import("@/lib/search/service");
const { createBookSourceResolver } = await import("@/lib/books/projects/sources");
const { buildDisasterExport } = await import("@/lib/export/service");
const { createContribution } = await import("@/lib/contributions/service");
const { createContributionAccessSnapshot, listVisibleContributionsForEvent, canReadContributionAsset } = await import("@/lib/authz/contribution-access");
const { POST: confirmHttp } = await import("@/app/api/mobile/v1/inbox/[id]/confirm/route");
const { PATCH: editHttp } = await import("@/app/api/mobile/v1/memories/[id]/route");
const { DeterministicFakeMemoryAssistant } = await import("@/lib/ai/fake");
const { requestEventSuggestions } = await import("@/lib/suggestions/service");
const { runAiWorkerOnce } = await import("@/jobs/runtime");
const { assetTranscript } = await import("@/db/schema/transcript");
afterAll(() => { closeDatabase(); for (const dir of dirs) rmSync(dir, { recursive: true, force: true }); });

it("grandparent recording: no child onboarding, mixed sources, HTTP, permissions, AI, browsing and portable restore", async () => {
  expect((await performSetup({ token: "grandparent-setup", displayName: "外公", email: "grandparent@fixture.invalid", password: "fixture-only-password" })).ok).toBe(true);
  const actor = getDb().select().from(user).get()!;
  const created = await completeOnboarding(actor.id, { familyName: "虚构祖辈家庭", timezone: "Asia/Shanghai", childDisplayName: "", childBirthDate: "", selfDisplayName: "外公", selfRelationToChild: "外公", selfIsGuardian: false });
  if (!created.ok) throw new Error(created.error);
  const familyId = created.familyId;
  const binding = await getUserBinding(actor.id);
  const context: FamilyContext = { userId: actor.id, userName: actor.name, familyId, personId: binding.personId, role: binding.role, accountEnabled: true, isGuardian: false, familyTimezone: "Asia/Shanghai", childLaterUnlockAge: 18 };
  expect((await listPeople(familyId)).map(p => p.isChild)).toEqual([false]);
  const bytes = readFileSync(path.join(__dirname, "../fixtures/sample.wav"));
  const stored = await ingestMedia({ kind: "audio", familyId, createdByUserId: actor.id, filename: "祖辈口述.wav", declaredMime: "audio/wav", buffer: bytes, clientLastModifiedMs: null });
  if (stored.status !== "stored") throw new Error("fixture audio not stored");
  const sound = await createInboxItemForAsset(familyId, stored.asset);
  const text = await createTextInboxItem(familyId, "年轻时在江边划船的故事");
  const merged = await mergeInboxEntries(familyId, [sound.id, text.id], { title: "外公讲年轻时候的故事", occurredAt: new Date("2026-09-07T09:00:00Z"), participantPersonIds: [binding.personId!] });
  if (!merged.ok) throw new Error(merged.error);
  const id = merged.eventId;
  expect((await getMemoryEventDetail(familyId, id))?.event).toMatchObject({ childPersonId: null, ageDays: null });
  expect((await getMobileMemory(context, id))).toMatchObject({ childPersonId: null, ageLabel: null, sourceNotes: [{ id: text.id, text: "年轻时在江边划船的故事" }] });
  expect(await canReadContributionAsset(createContributionAccessSnapshot(context), stored.asset.id)).toBe(true);
  expect((await getTimelinePage(context)).entries.map(e => e.event.id)).toContain(id);
  expect(JSON.stringify(await getCalendarMonth(context, "2026-09"))).toContain("2026-09-07");
  expect((await getHomeDashboard(context)).recentMemories[0].ageLabel).toBeNull();
  expect(searchFamily(context, { q: "年轻" }).events.map(e => e.id)).toContain(id);
  expect(createBookSourceResolver(context, "personal")("memory", id).state).toMatchObject({ available: true, ageLabel: null });
  expect((await getMobileSyncPage({ context })).events.find(e => e.id === id)?.ageLabel).toBeNull();

  const secret = await createContribution(familyId, { memoryEventId: id, authorPersonId: binding.personId!, recordedByUserId: actor.id, rawText: "私密船票", visibility: "private" });
  expect(secret.ok).toBe(true);
  const visitorId = randomUUID();
  getDb().insert(user).values({ id: visitorId, name: "读者", email: "reader@fixture.invalid", role: "viewer", familyId }).run();
  const visitor = { ...context, userId: visitorId, userName: "读者", personId: null, role: "viewer" as const };
  expect((await listVisibleContributionsForEvent(createContributionAccessSnapshot(context), id))).toHaveLength(1);
  expect((await listVisibleContributionsForEvent(createContributionAccessSnapshot(visitor), id))).toEqual([]);
  expect(searchFamily(visitor, { q: "私密船票" }).events).toEqual([]);

  // Adding a child as participant never rewrites the anchor; explicit adult anchor uses years.
  const child = await addPerson(familyId, { displayName: "孙辈", isChild: true, birthDate: "2026-09-01" });
  if (!child.ok) throw new Error("fixture child missing");
  expect((await updateMemoryEvent(familyId, id, actor.id, { participantPersonIds: [child.personId] })).ok).toBe(true);
  expect((await getMobileMemory(context, id))?.ageLabel).toBeNull();
  getDb().update(person).set({ birthDate: "1950-01-01" }).where(eq(person.id, binding.personId!)).run();
  expect((await updateMemoryEvent(familyId, id, actor.id, { childPersonId: binding.personId! })).ok).toBe(true);
  expect((await getMobileMemory(context, id))?.ageLabel).toBe("76 岁");
  expect((await getMemoryEventDetail(familyId, id))?.participants.map(p => p.id)).toEqual([child.personId]);

  const token = randomUUID();
  getDb().insert(session).values({ id: randomUUID(), token, userId: actor.id, expiresAt: new Date(Date.now() + 3600000) }).run();
  const request = (body: unknown) => new Request("http://localhost/api/mobile/v1/memories/fixture", { method: "PATCH", headers: { authorization: `Bearer ${token}`, "content-type": "application/json" }, body: JSON.stringify(body) });
  const edited = await editHttp(request({ childPersonId: null, title: "外公讲年轻时候的故事", expectedRevision: getDb().select().from(memoryEvent).where(eq(memoryEvent.id, id)).get()!.titleRevision, mutationId: randomUUID() }), { params: Promise.resolve({ id }) });
  expect(edited.status).toBe(200);
  expect(await edited.json()).toMatchObject({ childPersonId: null, ageLabel: null });
  expect((await editHttp(request({ childPersonId: "foreign-person", expectedRevision: getDb().select().from(memoryEvent).where(eq(memoryEvent.id, id)).get()!.titleRevision, mutationId: randomUUID() }), { params: Promise.resolve({ id }) })).status).toBe(400);
  const second = await createTextInboxItem(familyId, "夫妻旅行");
  const confirmed = await confirmHttp(request({}), { params: Promise.resolve({ id: second.id }) });
  expect(confirmed.status).toBe(201);
  const secondId = (await confirmed.json()).memoryEventId;
  expect(getDb().select().from(memoryEvent).where(eq(memoryEvent.id, secondId)).get()?.childPersonId).toBeNull();
  const empty = await createTextInboxItem(familyId, "没有任何参与人");
  const entry = (await getInboxEntry(familyId, empty.id))!;
  expect((await confirmInboxEntry(familyId, entry)).ok).toBe(true);

  const ai = new DeterministicFakeMemoryAssistant();
  vi.spyOn(ai, "generateText").mockResolvedValue({ text: JSON.stringify({ title: "江边的往事", locationText: null, facts: [], occurredAt: null, timePrecision: "approximate", personNames: [], tags: [] }), finishReason: "stop", provenance: { providerId: ai.provider.id, providerName: ai.provider.displayName, model: ai.capabilities.text.model! } });
  expect(requestEventSuggestions(context, id, { runtime: ai }).ok).toBe(true);
  for (let n = 0; n < 4; n++) await runAiWorkerOnce({ assistant: ai });
  expect(getDb().select().from(assetTranscript).where(eq(assetTranscript.assetId, stored.asset.id)).get()).toBeTruthy();
  expect((await getMemoryEventDetail(familyId, id))?.event.title).toBe("外公讲年轻时候的故事");

  const archive = await buildDisasterExport(familyId, { actorUserId: actor.id });
  const zipBytes = readFileSync(archive.filePath);
  const zip = await JSZip.loadAsync(zipBytes);
  const md = await zip.file(Object.keys(zip.files).find(name => name.endsWith("/timeline.md"))!)!.async("string");
  expect(md).not.toMatch(/宝宝|个月|百天|出生当天/);
  closeDatabase();
  process.env.DATA_DIR = dirs[1];
  vi.resetModules();
  const targetDb = await import("@/db");
  try {
    const targetSetup = await import("@/lib/auth/setup");
    expect((await targetSetup.performSetup({ token: "grandparent-setup", displayName: "恢复管理员", email: "restore@fixture.invalid", password: "fixture-only-password" })).ok).toBe(true);
    const operator = targetDb.getDb().get<{ id: string }>(sql`select id from user`)!;
    const { restoreFromZip } = await import("@/lib/restore/service");
    expect((await restoreFromZip(zipBytes, operator.id)).events).toBe(3);
    const restored = await (await import("@/lib/memories/service")).getMemoryEventDetail(familyId, id);
    expect(restored?.event.childPersonId).toBeNull();
    expect(restored?.participants.map(p => p.id)).toEqual([child.personId]);
    expect(restored?.assets.map(a => a.sha256)).toEqual([stored.asset.sha256]);
    expect(targetDb.getDb().all(sql`pragma foreign_key_check`)).toEqual([]);
  } finally { targetDb.closeDatabase(); }
});
