import { randomUUID } from 'node:crypto';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { eq } from 'drizzle-orm';
import { afterAll, expect, it } from 'vitest';
const directory = mkdtempSync(path.join(tmpdir(), 'ftc-voice-'));
process.env.DATA_DIR = directory;
process.env.AUTH_SECRET = 'growth-fixture-secret-only';
process.env.INITIAL_SETUP_TOKEN = 'growth-setup';
const { getDb, closeDatabase } = await import('@/db');
const { performSetup } = await import('@/lib/auth/setup');
const { user } = await import('@/db/schema/auth');
const { person } = await import('@/db/schema/family');
const { memoryEvent } = await import('@/db/schema/memory');
const { completeOnboarding, getUserBinding } = await import('@/lib/family/service');
const { saveDraft, publishDraft } = await import('@/lib/drafts/service');
const { emptyDraftContent } = await import('@/lib/drafts/model');
const { openGrowthBook } = await import('@/lib/growth/service');
const { createContribution } = await import('@/lib/contributions/service');
expect((await performSetup({token:'growth-setup',displayName:'爸爸',email:'growth@fixture.invalid',password:'fictional-password'})).ok).toBe(true);
const actor = getDb().select().from(user).get()!;
await completeOnboarding(actor.id,{familyName:'测试家庭',timezone:'Asia/Shanghai',childDisplayName:'小美',childBirthDate:'2026-01-31',selfDisplayName:'爸爸',selfRelationToChild:'爸爸'});
const binding = await getUserBinding(actor.id);
const context = {...binding,userId:actor.id,userName:actor.name,familyId:binding.familyId!,familyTimezone:binding.familyTimezone!,childLaterUnlockAge:binding.childLaterUnlockAge!};
function memory(text:string, occurredAt:string, extra = {}) {
  const draft = saveDraft(context,randomUUID(),0,randomUUID(),{...emptyDraftContent(),text,occurredAt,occurredAtPrecision:'date_only',...extra});
  return publishDraft(context,draft.id,draft.revision).memoryEventId!;
}
const { storeOriginal } = await import('@/lib/assets/service');
const { contribution } = await import('@/db/schema/contribution');
const { asset } = await import('@/db/schema/asset');
const { getDraft } = await import('@/lib/drafts/service');
const memoryId = memory('出生那天','2026-01-31T00:00:00Z');
const stored = await storeOriginal({familyId:context.familyId,createdByUserId:actor.id,type:'audio',timeSource:'import_time',mimeType:'audio/wav',originalFilename:'爸爸的声音.wav',extension:'wav',buffer:(await import('node:fs')).readFileSync(path.join(process.cwd(),'tests/fixtures/sample.wav'))});
if(stored.status!=='stored')throw Error('fixture failed');
const audioId=stored.asset.id;
const input={memoryEventId:memoryId,authorPersonId:context.personId!,recordedByUserId:actor.id,audioAssetId:audioId,visibility:'family' as const};
afterAll(()=>{closeDatabase();rmSync(directory,{recursive:true,force:true});});
it('saves audio-only words once and closes only the owning recording draft',async()=>{
  const id=randomUUID(), originalId=randomUUID();
  const draft=saveDraft(context,id,0,randomUUID(),{...emptyDraftContent(),visibility:'private',items:[{id:originalId,localCaptureRef:originalId,assetId:audioId,caption:''}]});
  const payload={...input,clientId:id,sourceDraftId:id};
  const first=await createContribution(context.familyId,payload);
  expect(first).toEqual({ok:true,contributionId:id});
  expect(await createContribution(context.familyId,payload)).toEqual(first);
  expect(getDb().select().from(contribution).all()).toHaveLength(1);
  expect(getDraft(context,id)).toMatchObject({status:'published',memoryEventId:memoryId,revision:draft.revision+1});
  expect(await createContribution(context.familyId,{...payload,rawText:'changed'})).toEqual({ok:false,error:'invalid'});
  const book=openGrowthBook(context);
  expect(book.readingMedia?.some(item=>item.asset?.id===audioId)).toBe(true);
  expect(book.sources.some(s=>s.contributionId===id)).toBe(true);
});
it('rejects non-audio, foreign assets, unbound drafts, impersonation, and hidden parents',async()=>{
  const reject=async(extra={})=>expect((await createContribution(context.familyId,{...input,clientId:randomUUID(),...extra})).ok).toBe(false);
  await reject({sourceDraftId:randomUUID()});
  getDb().update(asset).set({type:'image'}).where(eq(asset.id,audioId)).run();await reject();
  getDb().update(asset).set({type:'audio'}).where(eq(asset.id,audioId)).run();
  await reject({audioAssetId:randomUUID()});
  await reject({authorPersonId:randomUUID()});
  const bound=getDb().select().from(person).all().find(p=>p.isChild)!;
  getDb().insert(user).values({...actor,id:randomUUID(),personId:bound.id,email:'other-voice@fixture.invalid',familyId:context.familyId,role:'admin'}).run();
  await reject({authorPersonId:bound.id});
  getDb().update(memoryEvent).set({deletedAt:new Date()}).where(eq(memoryEvent.id,memoryId)).run();await reject();
  getDb().update(memoryEvent).set({deletedAt:null}).where(eq(memoryEvent.id,memoryId)).run();
  getDb().update(user).set({role:'viewer'}).where(eq(user.id,actor.id)).run();await reject();
});
