import { StyleSheet } from "react-native";

import { journalColors, journalRadius, journalSpace, journalType } from "./design/tokens";

export const colors = journalColors;

export const sharedStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.paper },
  content: { padding: journalSpace.page, paddingBottom: 120, gap: journalSpace.medium },
  eyebrow: {
    color: colors.coral,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.2,
  },
  title: { color: colors.ink, fontSize: journalType.title, fontWeight: "700" },
  intro: { color: colors.muted, fontSize: journalType.body },
  card: {
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: journalRadius.card,
    borderWidth: 1,
    padding: 16,
    gap: 9,
  },
  cardTitle: { color: colors.ink, fontSize: journalType.heading, fontWeight: "600" },
  body: { color: colors.muted, fontSize: journalType.body },
  label: { color: colors.ink, fontSize: journalType.label, fontWeight: "600" },
  input: {
    minHeight: 48,
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: journalRadius.control,
    borderWidth: 1,
    color: colors.ink,
    fontSize: 16,
    paddingHorizontal: 13,
    paddingVertical: 11,
  },
  primaryButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.coral,
    borderRadius: journalRadius.control,
    paddingHorizontal: 16,
  },
  primaryText: { color: "#FFFFFF", fontSize: 15, fontWeight: "700" },
  secondaryButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderColor: colors.line,
    backgroundColor: colors.card,
    borderRadius: journalRadius.control,
    borderWidth: 1,
    paddingHorizontal: 16,
  },
  secondaryText: { color: colors.coralDark, fontSize: 15, fontWeight: "700" },
  notice: { backgroundColor: colors.softSage, borderRadius: 12, padding: 12 },
  noticeText: { color: colors.sage, fontSize: 13 },
  warning: { backgroundColor: "#FFF1D9", borderRadius: 12, padding: 12 },
  warningText: { color: colors.warning, fontSize: 13 },
  error: { color: colors.error, fontSize: 13 },
  empty: { flex: 1, alignItems: "center", justifyContent: "center", padding: 32, gap: 9 },
  emptyTitle: { color: colors.ink, fontSize: 20, fontWeight: "700", textAlign: "center" },
  emptyText: { color: colors.muted, fontSize: 14, textAlign: "center" },
  pressed: { opacity: 0.7 },
  disabled: { opacity: 0.5 },
});
