import { StyleSheet } from "react-native";

export const colors = {
  ink: "#2F241F",
  muted: "#786B64",
  paper: "#FFF9F2",
  card: "#FFFFFF",
  line: "#EADDD0",
  coral: "#C9634D",
  coralDark: "#994734",
  sage: "#577566",
  softSage: "#E8F0EB",
  softCoral: "#F8E9E3",
  warning: "#9A651C",
  error: "#A52C2C",
};

export const sharedStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.paper },
  content: { padding: 18, paddingBottom: 44, gap: 14 },
  eyebrow: {
    color: colors.coral,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.2,
  },
  title: { color: colors.ink, fontSize: 28, lineHeight: 34, fontWeight: "800" },
  intro: { color: colors.muted, fontSize: 14, lineHeight: 21 },
  card: {
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    padding: 16,
    gap: 9,
  },
  cardTitle: { color: colors.ink, fontSize: 17, lineHeight: 23, fontWeight: "800" },
  body: { color: colors.muted, fontSize: 14, lineHeight: 21 },
  label: { color: colors.ink, fontSize: 13, fontWeight: "700" },
  input: {
    minHeight: 48,
    backgroundColor: colors.paper,
    borderColor: colors.line,
    borderRadius: 12,
    borderWidth: 1,
    color: colors.ink,
    fontSize: 16,
    paddingHorizontal: 13,
    paddingVertical: 11,
  },
  primaryButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.coral,
    borderRadius: 13,
    paddingHorizontal: 16,
  },
  primaryText: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" },
  secondaryButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderColor: colors.coral,
    borderRadius: 13,
    borderWidth: 1.5,
    paddingHorizontal: 16,
  },
  secondaryText: { color: colors.coralDark, fontSize: 15, fontWeight: "800" },
  notice: { backgroundColor: colors.softSage, borderRadius: 12, padding: 12 },
  noticeText: { color: colors.sage, fontSize: 13, lineHeight: 19 },
  warning: { backgroundColor: "#FFF1D9", borderRadius: 12, padding: 12 },
  warningText: { color: colors.warning, fontSize: 13, lineHeight: 19 },
  error: { color: colors.error, fontSize: 13, lineHeight: 19 },
  empty: { flex: 1, alignItems: "center", justifyContent: "center", padding: 32, gap: 9 },
  emptyTitle: { color: colors.ink, fontSize: 20, fontWeight: "800", textAlign: "center" },
  emptyText: { color: colors.muted, fontSize: 14, lineHeight: 21, textAlign: "center" },
  pressed: { opacity: 0.7 },
  disabled: { opacity: 0.5 },
});
