#!/usr/bin/env node
// Build the production-only operational CLIs as self-contained ESM bundles.
// The runner image copies only these emitted files; it does not need TS sources,
// tsx, or the repository's private/local state.
import { rm } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(rootDir, ".next", "ops");

await rm(outDir, { recursive: true, force: true });

await build({
  absWorkingDir: rootDir,
  entryPoints: {
    // Resolve from this script rather than the caller's current directory;
    // every entry remains inside the checked-out project.
    healthcheck: path.join(rootDir, "scripts", "healthcheck.mjs"),
    worker: path.join(rootDir, "jobs", "worker.ts"),
    restore: path.join(rootDir, "scripts", "restore.ts"),
    "smoke-deployment": path.join(rootDir, "scripts", "smoke-deployment.mjs"),
    "verify-export": path.join(rootDir, "scripts", "verify-export.mjs"),
  },
  outdir: outDir,
  outExtension: { ".js": ".mjs" },
  entryNames: "[name]",
  bundle: true,
  alias: {
    "server-only": path.join(rootDir, "scripts", "server-only-stub.mjs"),
  },
  platform: "node",
  target: "node24",
  format: "esm",
  charset: "utf8",
  legalComments: "none",
  sourcemap: false,
  minify: false,
  treeShaking: true,
  // Native addon resolution must remain relative to the final image's traced
  // node_modules. Everything else is bundled into the four CLI artifacts.
  external: ["better-sqlite3"],
  // Some transitive CommonJS libraries (archiver/lazystream) retain dynamic
  // built-in requires after bundling. Provide Node's real require in the ESM
  // wrapper so the production artifact can load them without shipping sources.
  banner: {
    js: `// Generated by scripts/build-ops.mjs; do not edit.
import { createRequire as __createRequire } from "node:module";
const require = __createRequire(import.meta.url);`,
  },
  logLevel: "info",
});
