import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash, randomBytes } from 'node:crypto';
import { existsSync, mkdtempSync, readdirSync, rmSync, utimesSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Readable } from 'node:stream';
import Database from 'better-sqlite3';
import { DEFAULT_BACKUP_LIMIT, Store } from '../src/store.ts';
import { createApp } from '../src/app.ts';
import { hashPassword } from '../src/passwords.ts';
import { BackupStore, OBJECT_LIMIT } from '../src/backup-store.ts';

const PW='12345678',HASH=await hashPassword(PW);
const sha=(b:Uint8Array)=>createHash('sha256').update(b).digest('hex');
const oid=(n:number)=>n.toString(16).padStart(64,'0');
const octet={'content-type':'application/octet-stream'};
function fixture() {
 const dir=mkdtempSync(join(tmpdir(),'anan-backup-test-'));
 const store=new Store(':memory:'),backups=new BackupStore(dir);
 const app=createApp(store,async()=>{throw new Error('no provider in this test');},'test',backups);
 const owner=store.setup('主人',HASH,'主人手机');
 store.createMember('家人',HASH);const member=store.attach(store.byUsername('家人')!.id,'家人手机');
 store.createMember('外婆',HASH);const other=store.attach(store.byUsername('外婆')!.id,'外婆手机');
 const headers=(token=member.token,extra:Record<string,string>={})=>({authorization:`Bearer ${token}`,...extra});
 const put=(id:string,bytes:Buffer,token=member.token,digestHex=sha(bytes))=>app.inject({method:'PUT',url:`/api/v1/backup/objects/${id}`,headers:headers(token,{...octet,'x-object-sha256':digestHex}),payload:bytes});
 const close=async()=>{await app.close();store.close();rmSync(dir,{recursive:true,force:true});};
 return {dir,store,backups,app,owner,member,other,headers,put,close};
}
test('objects round-trip byte for byte; repeats are idempotent and temp files never linger',async()=>{
 const f=fixture();const bytes=randomBytes(300000);
 const first=await f.put(oid(1),bytes);
 assert.equal(first.statusCode,201);assert.deepEqual(first.json(),{id:oid(1),bytes:300000});
 assert.equal((await f.put(oid(1),bytes)).statusCode,200);
 const got=await f.app.inject({url:`/api/v1/backup/objects/${oid(1)}`,headers:f.headers()});
 assert.equal(got.statusCode,200);assert.equal(got.headers['content-type'],'application/octet-stream');assert.equal(got.headers['content-length'],'300000');
 assert.ok(got.rawPayload.equals(bytes));
 assert.ok(existsSync(join(f.dir,f.member.member.id,'objects','00',oid(1))));
 assert.deepEqual(readdirSync(join(f.dir,'tmp')),[]);
 const status=(await f.app.inject({url:'/api/v1/backup/status',headers:f.headers()})).json();
 assert.equal(status.objects,1);assert.equal(status.bytes,300000);assert.equal(status.keyId,null);assert.equal(status.limitBytes,DEFAULT_BACKUP_LIMIT);assert.ok(status.freeBytes>0);
 await f.close();
});
test('mismatched, empty or malformed uploads are rejected and leave nothing behind',async()=>{
 const f=fixture();const bytes=randomBytes(1000);
 const wrong=await f.put(oid(2),bytes,f.member.token,sha(Buffer.from('other')));
 assert.equal(wrong.statusCode,400);assert.equal(wrong.json().code,'OBJECT_CORRUPT');
 assert.equal(f.backups.stat(f.member.member.id,oid(2)),null);
 assert.equal((await f.put(oid(2),Buffer.alloc(0))).statusCode,400);
 assert.equal((await f.app.inject({method:'PUT',url:`/api/v1/backup/objects/${oid(2)}`,headers:f.headers(f.member.token,octet),payload:bytes})).statusCode,400);
 assert.equal((await f.app.inject({method:'PUT',url:'/api/v1/backup/objects/not-hex',headers:f.headers(f.member.token,{...octet,'x-object-sha256':sha(bytes)}),payload:bytes})).statusCode,400);
 assert.equal((await f.app.inject({method:'PUT',url:`/api/v1/backup/objects/${oid(2)}`,headers:f.headers(f.member.token,{'content-type':'text/plain','x-object-sha256':sha(bytes)}),payload:'plain text'})).statusCode,415);
 assert.deepEqual(readdirSync(join(f.dir,'tmp')),[]);
 await f.close();
});
test('oversize uploads get 413 whether or not the length was declared',async()=>{
 const f=fixture();const big=Buffer.alloc(OBJECT_LIMIT+1,7);
 const declared=await f.put(oid(3),big);
 assert.equal(declared.statusCode,413);assert.equal(declared.json().code,'TOO_LARGE');
 const undeclared=await f.app.inject({method:'PUT',url:`/api/v1/backup/objects/${oid(3)}`,headers:f.headers(f.member.token,{...octet,'x-object-sha256':sha(big)}),payload:Readable.from([big.subarray(0,OBJECT_LIMIT),big.subarray(OBJECT_LIMIT)])});
 assert.equal(undeclared.statusCode,413);assert.equal(undeclared.json().code,'TOO_LARGE');
 assert.equal(f.backups.stat(f.member.member.id,oid(3)),null);
 assert.deepEqual(readdirSync(join(f.dir,'tmp')),[]);
 await f.close();
});
test('quota and the disk floor are enforced; a repeat of an existing object always succeeds',async()=>{
 const f=fixture();
 f.store.editMember(f.member.member.id,{enabled:true,photoLimit:100,writeLimit:20,backupLimitBytes:1000});
 const over=await f.put(oid(4),randomBytes(2000));
 assert.equal(over.statusCode,413);assert.equal(over.json().code,'QUOTA_FULL');
 const streamed=randomBytes(2000);
 const late=await f.app.inject({method:'PUT',url:`/api/v1/backup/objects/${oid(4)}`,headers:f.headers(f.member.token,{...octet,'x-object-sha256':sha(streamed)}),payload:Readable.from([streamed])});
 assert.equal(late.statusCode,413);assert.equal(late.json().code,'QUOTA_FULL');
 assert.equal(f.backups.stat(f.member.member.id,oid(4)),null);
 const fits=randomBytes(800);
 assert.equal((await f.put(oid(5),fits)).statusCode,201);
 f.store.editMember(f.member.member.id,{enabled:true,photoLimit:100,writeLimit:20,backupLimitBytes:500});
 assert.equal((await f.put(oid(5),fits)).statusCode,200);
 assert.equal((await f.put(oid(6),randomBytes(10))).statusCode,413);
 f.backups.freeBytes=async()=>0;
 const full=await f.put(oid(7),randomBytes(10));
 assert.equal(full.statusCode,507);assert.equal(full.json().code,'SERVER_FULL');
 await f.close();
});
test('a member may run two uploads at once; the third is told to wait, other members are unaffected',async()=>{
 const f=fixture();
 const bodies=[randomBytes(5000),randomBytes(6000)],streams=bodies.map(()=>new Readable({read(){}}));
 const pending=streams.map((stream,i)=>f.app.inject({method:'PUT',url:`/api/v1/backup/objects/${oid(10+i)}`,headers:f.headers(f.member.token,{...octet,'x-object-sha256':sha(bodies[i]!)}),payload:stream}));
 await new Promise(resolve=>setTimeout(resolve,50));
 const third=await f.put(oid(12),randomBytes(10));
 assert.equal(third.statusCode,429);assert.equal(third.json().code,'BUSY');
 assert.equal((await f.put(oid(13),randomBytes(10),f.other.token)).statusCode,201);
 streams.forEach((stream,i)=>{stream.push(bodies[i]);stream.push(null);});
 for(const response of await Promise.all(pending))assert.equal(response.statusCode,201);
 assert.equal((await f.put(oid(12),randomBytes(10))).statusCode,201);
 await f.close();
});
test('have and prune see only the caller; prune spares fresh objects and everything in keep',async()=>{
 const f=fixture();const a=randomBytes(100),b=randomBytes(200);
 assert.equal((await f.put(oid(20),a)).statusCode,201);assert.equal((await f.put(oid(21),b)).statusCode,201);
 assert.equal((await f.put(oid(22),randomBytes(50),f.other.token)).statusCode,201);
 const have=await f.app.inject({method:'POST',url:'/api/v1/backup/objects/have',headers:f.headers(),payload:{ids:[oid(20),oid(21),oid(22),oid(23)]}});
 assert.deepEqual(have.json(),{missing:[oid(22),oid(23)]});
 assert.equal((await f.app.inject({url:`/api/v1/backup/objects/${oid(22)}`,headers:f.headers()})).statusCode,404);
 assert.deepEqual((await f.app.inject({method:'POST',url:'/api/v1/backup/prune',headers:f.headers(),payload:{keep:[oid(20)]}})).json(),{removed:0,bytes:0});
 const old=new Date(Date.now()-7200000);
 for(const id of [oid(20),oid(21)])utimesSync(f.backups.objectPath(f.member.member.id,id),old,old);
 utimesSync(f.backups.objectPath(f.other.member.id,oid(22)),old,old);
 assert.deepEqual((await f.app.inject({method:'POST',url:'/api/v1/backup/prune',headers:f.headers(),payload:{keep:[oid(20)]}})).json(),{removed:1,bytes:200});
 assert.equal(f.backups.stat(f.member.member.id,oid(20)),100);
 assert.equal(f.backups.stat(f.member.member.id,oid(21)),null);
 assert.equal(f.backups.stat(f.other.member.id,oid(22)),50);
 assert.equal((await f.app.inject({method:'POST',url:'/api/v1/backup/objects/have',headers:f.headers(),payload:{ids:['nope']}})).statusCode,400);
 await f.close();
});
test('the manifest index round-trips and its key id shows in status',async()=>{
 const f=fixture();
 assert.equal((await f.app.inject({url:'/api/v1/backup/manifest',headers:f.headers()})).statusCode,404);
 const index=randomBytes(100).toString('base64'),keyId='00ff00ff00ff00ff';
 const put=await f.app.inject({method:'PUT',url:'/api/v1/backup/manifest',headers:f.headers(),payload:{keyId,index}});
 assert.equal(put.statusCode,200);assert.ok(Number.isFinite(Date.parse(put.json().updatedAt)));
 const got=(await f.app.inject({url:'/api/v1/backup/manifest',headers:f.headers()})).json();
 assert.equal(got.keyId,keyId);assert.equal(got.index,index);assert.equal(got.updatedAt,put.json().updatedAt);
 assert.equal((await f.app.inject({url:'/api/v1/backup/status',headers:f.headers()})).json().keyId,keyId);
 assert.equal((await f.app.inject({url:'/api/v1/backup/manifest',headers:f.headers(f.other.token)})).statusCode,404);
 for(const bad of [{keyId:'short',index},{keyId,index:'not base64!'},{keyId,index:'A'.repeat(90001)},{keyId,index,extra:1}])
  assert.equal((await f.app.inject({method:'PUT',url:'/api/v1/backup/manifest',headers:f.headers(),payload:bad})).statusCode,400);
 await f.close();
});
test('deleting a backup removes objects and manifest; the owner can do it per member and set the quota',async()=>{
 const f=fixture();
 assert.equal((await f.put(oid(30),randomBytes(10))).statusCode,201);
 assert.equal((await f.app.inject({method:'PUT',url:'/api/v1/backup/manifest',headers:f.headers(),payload:{keyId:'0123456789abcdef',index:'QUJD'}})).statusCode,200);
 assert.deepEqual((await f.app.inject({method:'DELETE',url:'/api/v1/backup',headers:f.headers()})).json(),{ok:true});
 const status=(await f.app.inject({url:'/api/v1/backup/status',headers:f.headers()})).json();
 assert.equal(status.objects,0);assert.equal(status.keyId,null);
 assert.ok(!existsSync(join(f.dir,f.member.member.id)));
 assert.equal((await f.put(oid(31),randomBytes(10))).statusCode,201);
 const memberId=f.member.member.id;
 assert.equal((await f.app.inject({method:'PATCH',url:`/api/v1/admin/members/${memberId}`,headers:f.headers(),payload:{enabled:true,photoLimit:1,writeLimit:1,backupLimitBytes:123}})).statusCode,403);
 assert.equal((await f.app.inject({method:'PATCH',url:`/api/v1/admin/members/${memberId}`,headers:f.headers(f.owner.token),payload:{enabled:true,photoLimit:1,writeLimit:1,backupLimitBytes:123}})).statusCode,200);
 assert.equal(f.store.memberById(memberId).backup_limit_bytes,123);
 assert.equal((await f.app.inject({method:'PATCH',url:`/api/v1/admin/members/${memberId}`,headers:f.headers(f.owner.token),payload:{enabled:true,photoLimit:2,writeLimit:2}})).statusCode,200);
 assert.equal(f.store.memberById(memberId).backup_limit_bytes,123);
 const overview=(await f.app.inject({url:'/api/v1/admin/overview',headers:f.headers(f.owner.token)})).json();
 const row=overview.members.find((m:{id:string})=>m.id===memberId);
 assert.deepEqual(row.backup,{objects:1,bytes:10,limitBytes:123});assert.ok(overview.backupFreeBytes>0);
 assert.equal((await f.app.inject({method:'DELETE',url:`/api/v1/admin/members/${memberId}/backup`,headers:f.headers()})).statusCode,403);
 assert.equal((await f.app.inject({method:'DELETE',url:`/api/v1/admin/members/${memberId}/backup`,headers:f.headers(f.owner.token)})).statusCode,200);
 assert.equal(f.backups.stat(memberId,oid(31)),null);
 assert.equal((await f.app.inject({method:'DELETE',url:`/api/v1/admin/members/00000000-0000-4000-8000-000000000000/backup`,headers:f.headers(f.owner.token)})).statusCode,404);
 await f.close();
});
test('backup routes require a login',async()=>{
 const f=fixture();
 for(const [method,url] of [['GET','/api/v1/backup/status'],['POST','/api/v1/backup/objects/have'],['PUT',`/api/v1/backup/objects/${oid(1)}`],['GET',`/api/v1/backup/objects/${oid(1)}`],['PUT','/api/v1/backup/manifest'],['GET','/api/v1/backup/manifest'],['POST','/api/v1/backup/prune'],['DELETE','/api/v1/backup']] as const)
  assert.equal((await f.app.inject({method,url,headers:method==='PUT'&&url.includes('objects')?{...octet,'x-object-sha256':oid(1)}:{},payload:method==='GET'||method==='DELETE'?undefined:url.includes('objects/')&&method==='PUT'?Buffer.from('x'):{}})).statusCode,401,`${method} ${url}`);
 await f.close();
});
test('older databases gain the quota column with its default and stale temp files are swept',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'anan-backup-migrate-'));const file=join(dir,'old.sqlite');
 const raw=new Database(file);
 raw.exec("CREATE TABLE members(id TEXT PRIMARY KEY,name TEXT NOT NULL,role TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,photo_limit INTEGER NOT NULL DEFAULT 100,write_limit INTEGER NOT NULL DEFAULT 20,username TEXT,password_hash TEXT);INSERT INTO members(id,name,role,username,password_hash) VALUES('00000000-0000-4000-8000-000000000001','旧成员','owner','旧成员','x');");
 raw.close();
 const store=new Store(file);
 assert.equal(store.members()[0]!.backup_limit_bytes,DEFAULT_BACKUP_LIMIT);
 assert.equal(store.manifest('00000000-0000-4000-8000-000000000001'),undefined);
 store.close();
 const backups=new BackupStore(join(dir,'objects'));
 writeFileSync(join(dir,'objects','tmp','fresh.part'),'a');writeFileSync(join(dir,'objects','tmp','stale.part'),'b');
 const old=new Date(Date.now()-7200000);utimesSync(join(dir,'objects','tmp','stale.part'),old,old);
 backups.sweepTemp();
 assert.deepEqual(readdirSync(join(dir,'objects','tmp')),['fresh.part']);
 rmSync(dir,{recursive:true,force:true});
});
